"""Added nuke ubl

Revision ID: 2541a2c58e68
Revises: 
Create Date: 2023-05-09 19:54:48.685707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2541a2c58e68'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ubl', sa.Column('nuke_entitled', sa.Integer(), nullable=True))
    op.add_column('ubl', sa.Column('nuke_used', sa.Integer(), nullable=True))
    op.add_column('ubl', sa.Column('nuke_available', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ubl', 'nuke_available')
    op.drop_column('ubl', 'nuke_used')
    op.drop_column('ubl', 'nuke_entitled')
    # ### end Alembic commands ###
